// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(skylar_brockbankContext))]
    partial class skylar_brockbankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 6,
                            Name = "Doug The Dog",
                            Sex = "M",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 4,
                            Name = "Cleocatra",
                            Sex = "F",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 8,
                            Name = "Barkus Aurelius",
                            Sex = "M",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 5,
                            Name = "Droolius Caeser",
                            Sex = "M",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 6,
                            Name = "Ada Loves-Laces",
                            Sex = "F",
                            Type = "cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
